import {
  CheckCircle2,
  Code2,
  Download,
  File,
  Folder,
  GitCommit,
  Loader2,
  Play,
  RefreshCw,
  RotateCcw,
  Terminal,
} from "lucide-react";
import { AnimatePresence, motion } from "motion/react";
import { useEffect, useRef, useState } from "react";
import { toast } from "sonner";

// ─── Types ────────────────────────────────────────────────────────────────────

type StageStatus = "idle" | "running" | "complete";

interface Stage {
  id: string;
  label: string;
  emoji: string;
  desc: string;
}

interface FileNode {
  name: string;
  type: "file" | "dir";
  children?: FileNode[];
  content?: string;
}

interface Commit {
  version: string;
  message: string;
  time: string;
}

// ─── Static data ──────────────────────────────────────────────────────────────

const STAGES: Stage[] = [
  {
    id: "planner",
    label: "Planner",
    emoji: "🧠",
    desc: "Breaks goal into tasks",
  },
  {
    id: "architect",
    label: "Architect",
    emoji: "📐",
    desc: "Designs file structure",
  },
  {
    id: "developer",
    label: "Developer",
    emoji: "💻",
    desc: "Generates source code",
  },
  {
    id: "reviewer",
    label: "Reviewer",
    emoji: "✅",
    desc: "Validates & lints output",
  },
];

const PRESETS = ["React Todo App", "Weather Dashboard", "REST API", "Chat App"];

const FILE_TREES: Record<string, FileNode[]> = {
  default: [
    {
      name: "src",
      type: "dir",
      children: [
        {
          name: "App.tsx",
          type: "file",
          content: `import React from 'react';
import { TodoList } from './components/TodoList';
import './App.css';

export default function App() {
  return (
    <div className="app">
      <h1>Todo App</h1>
      <TodoList />
    </div>
  );
}`,
        },
        {
          name: "components",
          type: "dir",
          children: [
            {
              name: "TodoList.tsx",
              type: "file",
              content: `import { useState } from 'react';

interface Todo { id: number; text: string; done: boolean; }

export function TodoList() {
  const [todos, setTodos] = useState<Todo[]>([]);
  const [input, setInput] = useState('');

  const add = () => {
    if (!input.trim()) return;
    setTodos(prev => [...prev, { id: Date.now(), text: input, done: false }]);
    setInput('');
  };

  return (
    <div>
      <input value={input} onChange={e => setInput(e.target.value)} />
      <button onClick={add}>Add</button>
      <ul>{todos.map(t => <li key={t.id}>{t.text}</li>)}</ul>
    </div>
  );
}`,
            },
          ],
        },
      ],
    },
    {
      name: "package.json",
      type: "file",
      content: `{
  "name": "react-todo-app",
  "version": "1.0.0",
  "dependencies": {
    "react": "^19.0.0",
    "react-dom": "^19.0.0",
    "typescript": "^5.0.0"
  }
}`,
    },
    {
      name: "README.md",
      type: "file",
      content:
        "# React Todo App\n\nGenerated by PRIYA AI Developer Mode.\n\n## Setup\n\n```bash\nnpm install\nnpm run dev\n```",
    },
  ],
};

const COMMITS: Commit[] = [
  {
    version: "v1.0.2",
    message: "Added styles and responsive layout",
    time: "just now",
  },
  {
    version: "v1.0.1",
    message: "Fixed routing and navigation",
    time: "1 min ago",
  },
  {
    version: "v1.0.0",
    message: "Initial generation from goal",
    time: "3 min ago",
  },
];

const CONSOLE_LINES = [
  "[PLANNER] Analyzing goal...",
  "[PLANNER] Generated 7 subtasks",
  "[ARCHITECT] Designing component tree...",
  "[ARCHITECT] File structure ready",
  "[DEVELOPER] Generating App.tsx...",
  "[DEVELOPER] Generating TodoList.tsx...",
  "[DEVELOPER] Writing package.json...",
  "[REVIEWER] Running lint checks...",
  "[REVIEWER] ✗ Error: missing prop type in TodoList",
  "[SELF-CORRECTION] Detected 1 error — re-running Developer stage...",
  "[DEVELOPER] Patching TodoList.tsx prop types...",
  "[REVIEWER] All checks passed ✓",
  "[COMPLETE] Project generated successfully.",
];

// ─── FileTree component ───────────────────────────────────────────────────────

function FileTree({
  nodes,
  depth = 0,
  selectedFile,
  onSelect,
}: {
  nodes: FileNode[];
  depth?: number;
  selectedFile: string | null;
  onSelect: (f: FileNode) => void;
}) {
  return (
    <div>
      {nodes.map((node) => (
        <div key={node.name}>
          {node.type === "dir" ? (
            <div
              className="flex items-center gap-1.5 py-0.5 px-2 text-[11px] font-mono text-muted-foreground/70"
              style={{ paddingLeft: `${8 + depth * 12}px` }}
            >
              <Folder className="w-3 h-3 text-yellow-400/70" />
              {node.name}
            </div>
          ) : (
            <button
              type="button"
              onClick={() => onSelect(node)}
              className={`w-full flex items-center gap-1.5 py-0.5 text-[11px] font-mono transition-colors ${
                selectedFile === node.name
                  ? "text-primary bg-primary/10"
                  : "text-muted-foreground hover:text-foreground hover:bg-muted/20"
              }`}
              style={{ paddingLeft: `${8 + depth * 12}px` }}
              data-ocid={`ai-dev.file_${node.name.replace(/[^a-z0-9]/gi, "_").toLowerCase()}`}
            >
              <File className="w-3 h-3 text-primary/60" />
              {node.name}
            </button>
          )}
          {node.children && (
            <FileTree
              nodes={node.children}
              depth={depth + 1}
              selectedFile={selectedFile}
              onSelect={onSelect}
            />
          )}
        </div>
      ))}
    </div>
  );
}

// ─── Main Page ────────────────────────────────────────────────────────────────

export function AIDeveloperPage() {
  const [goal, setGoal] = useState("");
  const [stageStatuses, setStageStatuses] = useState<
    Record<string, StageStatus>
  >(Object.fromEntries(STAGES.map((s) => [s.id, "idle"])));
  const [isGenerating, setIsGenerating] = useState(false);
  const [isComplete, setIsComplete] = useState(false);
  const [selectedFile, setSelectedFile] = useState<FileNode | null>(null);
  const [consoleLines, setConsoleLines] = useState<string[]>([]);
  const [consoleIdx, setConsoleIdx] = useState(0);
  const [hasSelfCorrected, setHasSelfCorrected] = useState(false);
  const consoleRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (consoleRef.current) {
      consoleRef.current.scrollTop = consoleRef.current.scrollHeight;
    }
  });

  const handleGenerate = () => {
    if (!goal.trim()) return;
    setIsGenerating(true);
    setIsComplete(false);
    setConsoleLines([]);
    setConsoleIdx(0);
    setHasSelfCorrected(false);
    setStageStatuses(Object.fromEntries(STAGES.map((s) => [s.id, "idle"])));
    setSelectedFile(null);

    // Run stages sequentially
    STAGES.forEach((stage, i) => {
      setTimeout(() => {
        setStageStatuses((prev) => ({ ...prev, [stage.id]: "running" }));
        setTimeout(() => {
          setStageStatuses((prev) => ({ ...prev, [stage.id]: "complete" }));
          if (i === STAGES.length - 1) {
            setIsGenerating(false);
            setIsComplete(true);
          }
        }, 1400);
      }, i * 2800);
    });
  };

  // Stream console lines during generation
  useEffect(() => {
    if (!isGenerating && !isComplete) return;
    if (consoleIdx >= CONSOLE_LINES.length) return;
    const t = setTimeout(() => {
      setConsoleLines((prev) => [...prev, CONSOLE_LINES[consoleIdx]]);
      if (CONSOLE_LINES[consoleIdx].includes("SELF-CORRECTION"))
        setHasSelfCorrected(true);
      setConsoleIdx((i) => i + 1);
    }, 900);
    return () => clearTimeout(t);
  }, [isGenerating, isComplete, consoleIdx]);

  const allFiles = FILE_TREES.default;
  const flatFiles = (nodes: FileNode[]): FileNode[] =>
    nodes.flatMap((n) =>
      n.type === "file" ? [n] : flatFiles(n.children ?? []),
    );

  return (
    <div
      className="flex flex-col h-full min-h-0 scanline-overlay"
      data-ocid="ai-dev.page"
    >
      {/* Page header */}
      <div className="shrink-0 px-5 py-4 border-b border-primary/20 flex items-center gap-3 bg-card/60 backdrop-blur-sm">
        <div className="w-9 h-9 rounded-xl border border-primary/50 flex items-center justify-center glow-cyan">
          <Code2 className="w-5 h-5 text-primary" />
        </div>
        <div>
          <h1
            className="font-display font-bold text-base text-foreground tracking-widest uppercase"
            style={{ textShadow: "0 0 16px oklch(0.7 0.18 200 / 0.6)" }}
          >
            AI Developer Mode
          </h1>
          <p className="text-[10px] font-mono text-muted-foreground/60">
            Autonomous code generation · multi-file projects · self-correcting
            pipeline
          </p>
        </div>
        <div className="ml-auto flex items-center gap-2">
          {isGenerating && (
            <motion.span
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              className="flex items-center gap-1.5 text-[10px] font-mono text-primary px-2.5 py-1 rounded-lg border border-primary/40 bg-primary/10"
            >
              <Loader2 className="w-3 h-3 animate-spin" /> GENERATING
            </motion.span>
          )}
          {isComplete && (
            <span className="flex items-center gap-1.5 text-[10px] font-mono text-emerald-400 px-2.5 py-1 rounded-lg border border-emerald-400/40 bg-emerald-400/10">
              <CheckCircle2 className="w-3 h-3" /> COMPLETE
            </span>
          )}
        </div>
      </div>

      {/* Main 3-panel layout */}
      <div className="flex-1 min-h-0 grid grid-cols-[320px_1fr_260px] divide-x divide-primary/10 overflow-hidden">
        {/* LEFT: Goal + Pipeline + Files */}
        <div className="flex flex-col gap-3 p-4 overflow-y-auto">
          {/* Goal input */}
          <div
            className="glass-panel rounded-xl p-3 border border-primary/30"
            data-ocid="ai-dev.goal_panel"
          >
            <p className="hud-label text-primary mb-2">Project Goal</p>
            <textarea
              value={goal}
              onChange={(e) => setGoal(e.target.value)}
              placeholder="Describe the project you want Priya to build..."
              rows={3}
              className="w-full bg-background/40 border border-border/40 rounded-lg px-3 py-2 text-xs font-mono text-foreground placeholder:text-muted-foreground/40 focus:outline-none focus:border-primary/60 resize-none transition-smooth"
              data-ocid="ai-dev.goal_input"
            />
            {/* Preset chips */}
            <div className="flex flex-wrap gap-1.5 mt-2 mb-2">
              {PRESETS.map((p) => (
                <button
                  key={p}
                  type="button"
                  onClick={() => setGoal(p)}
                  className="text-[10px] font-mono px-2 py-0.5 rounded-full border border-primary/30 text-primary/70 hover:bg-primary/10 hover:text-primary transition-colors"
                  data-ocid={`ai-dev.preset_${p.toLowerCase().replace(/ /g, "_")}`}
                >
                  {p}
                </button>
              ))}
            </div>
            <button
              type="button"
              onClick={handleGenerate}
              disabled={!goal.trim() || isGenerating}
              className="w-full flex items-center justify-center gap-2 py-2 rounded-lg btn-cyan text-xs font-mono disabled:opacity-40 transition-all"
              data-ocid="ai-dev.generate_button"
            >
              {isGenerating ? (
                <>
                  <Loader2 className="w-3.5 h-3.5 animate-spin" /> Generating...
                </>
              ) : (
                <>
                  <Play className="w-3.5 h-3.5" /> Generate Project
                </>
              )}
            </button>
          </div>

          {/* Stage pipeline */}
          <div className="glass-panel rounded-xl p-3 border border-primary/20">
            <p className="hud-label text-muted-foreground/60 mb-2">Pipeline</p>
            <div className="space-y-2">
              {STAGES.map((stage, i) => {
                const status = stageStatuses[stage.id];
                return (
                  <motion.div
                    key={stage.id}
                    initial={{ opacity: 0, x: -8 }}
                    animate={{ opacity: 1, x: 0 }}
                    transition={{ delay: i * 0.07 }}
                    className={`flex items-center gap-2.5 p-2 rounded-lg border transition-all duration-300 ${
                      status === "running"
                        ? "border-primary/60 bg-primary/10 shadow-[0_0_12px_oklch(0.7_0.18_200/0.2)]"
                        : status === "complete"
                          ? "border-emerald-400/40 bg-emerald-400/5"
                          : "border-border/20 bg-transparent"
                    }`}
                    data-ocid={`ai-dev.stage_${stage.id}`}
                  >
                    <span className="text-base">{stage.emoji}</span>
                    <div className="flex-1 min-w-0">
                      <div className="flex items-center justify-between">
                        <span className="text-[11px] font-mono font-bold text-foreground">
                          {stage.label}
                        </span>
                        <span
                          className={`text-[9px] font-mono px-1.5 py-0.5 rounded-full border ${
                            status === "running"
                              ? "border-primary/60 text-primary bg-primary/10"
                              : status === "complete"
                                ? "border-emerald-400/50 text-emerald-400"
                                : "border-border/30 text-muted-foreground/40"
                          }`}
                        >
                          {status === "running"
                            ? "● RUNNING"
                            : status === "complete"
                              ? "✓ DONE"
                              : "○ IDLE"}
                        </span>
                      </div>
                      {/* Progress bar */}
                      <div className="mt-1.5 h-0.5 rounded-full bg-muted/30 overflow-hidden">
                        <motion.div
                          className="h-full rounded-full bg-gradient-to-r from-primary to-secondary"
                          animate={{
                            width:
                              status === "complete"
                                ? "100%"
                                : status === "running"
                                  ? "60%"
                                  : "0%",
                          }}
                          transition={{ duration: 0.6 }}
                        />
                      </div>
                    </div>
                    {status === "complete" && (
                      <CheckCircle2 className="w-3.5 h-3.5 text-emerald-400 shrink-0" />
                    )}
                    {status === "running" && (
                      <Loader2 className="w-3.5 h-3.5 text-primary animate-spin shrink-0" />
                    )}
                  </motion.div>
                );
              })}
            </div>
          </div>

          {/* File Tree */}
          {isComplete && (
            <motion.div
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              className="glass-panel rounded-xl border border-primary/20 overflow-hidden"
              data-ocid="ai-dev.file_tree"
            >
              <div className="px-3 py-2 border-b border-primary/10 flex items-center gap-2">
                <Folder className="w-3.5 h-3.5 text-yellow-400/70" />
                <span className="hud-label text-muted-foreground/60">
                  Generated Files
                </span>
              </div>
              <div className="py-1">
                <FileTree
                  nodes={allFiles}
                  selectedFile={selectedFile?.name ?? null}
                  onSelect={setSelectedFile}
                />
              </div>
            </motion.div>
          )}
        </div>

        {/* CENTER: Code viewer */}
        <div className="flex flex-col min-h-0 bg-card/20">
          {/* Code viewer header */}
          <div className="shrink-0 px-4 py-2.5 border-b border-primary/10 flex items-center gap-2">
            <Code2 className="w-3.5 h-3.5 text-primary/60" />
            <span className="text-[11px] font-mono text-muted-foreground/70">
              {selectedFile ? selectedFile.name : "Select a file to view code"}
            </span>
          </div>

          {/* Code area */}
          <div
            className="flex-1 overflow-auto p-4"
            data-ocid="ai-dev.code_viewer"
          >
            {selectedFile ? (
              <motion.pre
                key={selectedFile.name}
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                className="text-[11px] font-mono text-foreground/85 leading-relaxed whitespace-pre-wrap"
              >
                <code>{selectedFile.content}</code>
              </motion.pre>
            ) : isComplete ? (
              <div className="flex flex-col items-center justify-center h-full gap-3 text-center">
                <Code2 className="w-12 h-12 text-primary/20" />
                <p className="text-xs font-mono text-muted-foreground/50">
                  Click a file in the tree to view its code
                </p>
                <button
                  type="button"
                  onClick={() =>
                    setSelectedFile(flatFiles(allFiles)[0] ?? null)
                  }
                  className="text-xs font-mono text-primary hover:glow-cyan transition-smooth"
                >
                  Open App.tsx →
                </button>
              </div>
            ) : (
              <div className="flex flex-col items-center justify-center h-full gap-3 text-center">
                <Code2 className="w-12 h-12 text-primary/10" />
                <p className="text-xs font-mono text-muted-foreground/40">
                  Enter a goal and click Generate to start
                </p>
              </div>
            )}
          </div>

          {/* Debug console */}
          <div
            className="shrink-0 border-t border-primary/10"
            data-ocid="ai-dev.console"
          >
            <div className="px-4 py-2 flex items-center gap-2 border-b border-primary/10">
              <Terminal className="w-3.5 h-3.5 text-primary/60" />
              <span className="hud-label text-muted-foreground/60">
                Debug Console
              </span>
              {hasSelfCorrected && (
                <motion.span
                  initial={{ opacity: 0 }}
                  animate={{ opacity: 1 }}
                  className="ml-auto text-[10px] font-mono text-yellow-400 flex items-center gap-1"
                >
                  <RefreshCw className="w-3 h-3" /> Self-correction activated
                </motion.span>
              )}
            </div>
            <div
              ref={consoleRef}
              className="h-28 overflow-y-auto p-3 space-y-0.5 bg-black/20"
            >
              {consoleLines.length === 0 && (
                <p className="text-[10px] font-mono text-muted-foreground/30">
                  Waiting for generation...
                </p>
              )}
              {consoleLines.map((line, i) => (
                <motion.p
                  key={`console-${i}-${line.length}`}
                  initial={{ opacity: 0, x: -4 }}
                  animate={{ opacity: 1, x: 0 }}
                  className={`text-[10px] font-mono ${
                    line.includes("Error") || line.includes("✗")
                      ? "text-red-400"
                      : line.includes("SELF-CORRECTION")
                        ? "text-yellow-400 font-bold"
                        : line.includes("COMPLETE") || line.includes("passed")
                          ? "text-emerald-400"
                          : "text-muted-foreground/70"
                  }`}
                >
                  {line}
                </motion.p>
              ))}
            </div>
          </div>
        </div>

        {/* RIGHT: Version history + Export */}
        <div className="flex flex-col gap-3 p-4 overflow-y-auto">
          {/* Version history */}
          <div
            className="glass-panel rounded-xl border border-secondary/30 overflow-hidden"
            data-ocid="ai-dev.version_history"
          >
            <div className="px-3 py-2 border-b border-secondary/20 flex items-center gap-2">
              <GitCommit className="w-3.5 h-3.5 text-secondary" />
              <span className="hud-label text-secondary/80">
                Version History
              </span>
            </div>
            <div className="divide-y divide-secondary/10">
              {COMMITS.map((c, i) => (
                <motion.div
                  key={c.version}
                  initial={{ opacity: 0, x: 8 }}
                  animate={{ opacity: 1, x: 0 }}
                  transition={{ delay: i * 0.08 }}
                  className="px-3 py-2.5 flex items-start gap-2"
                  data-ocid={`ai-dev.commit.${i + 1}`}
                >
                  <div className="mt-0.5 w-5 h-5 rounded-full border border-secondary/40 bg-secondary/10 flex items-center justify-center shrink-0">
                    <GitCommit className="w-2.5 h-2.5 text-secondary" />
                  </div>
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center justify-between gap-1">
                      <span className="text-[10px] font-mono font-bold text-secondary">
                        {c.version}
                      </span>
                      <span className="text-[9px] font-mono text-muted-foreground/50">
                        {c.time}
                      </span>
                    </div>
                    <p className="text-[10px] font-mono text-muted-foreground/80 mt-0.5 line-clamp-2">
                      {c.message}
                    </p>
                    <button
                      type="button"
                      onClick={() => toast.info(`Rolled back to ${c.version}`)}
                      className="mt-1 text-[9px] font-mono text-primary/60 hover:text-primary transition-colors flex items-center gap-1"
                      data-ocid={`ai-dev.rollback.${i + 1}`}
                    >
                      <RotateCcw className="w-2.5 h-2.5" /> Rollback
                    </button>
                  </div>
                </motion.div>
              ))}
            </div>
          </div>

          {/* Export */}
          <div
            className="glass-panel rounded-xl p-3 border border-primary/20"
            data-ocid="ai-dev.export_panel"
          >
            <p className="hud-label text-muted-foreground/60 mb-2">
              Export Project
            </p>
            <button
              type="button"
              onClick={() => {
                if (!isComplete) {
                  toast.error("Generate a project first");
                  return;
                }
                toast.success("project.zip download started!");
              }}
              className="w-full flex items-center justify-center gap-2 py-2 rounded-lg border border-primary/40 text-primary text-xs font-mono hover:bg-primary/10 transition-colors"
              data-ocid="ai-dev.export_button"
            >
              <Download className="w-3.5 h-3.5" /> Export .zip
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
