/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AdminAction = { 'updateTier' : null } |
  { 'banUser' : null } |
  { 'uploadDoc' : null } |
  { 'reindex' : null } |
  { 'deleteDoc' : null };
export interface AdminLog {
  'id' : bigint,
  'action' : AdminAction,
  'target' : string,
  'timestamp' : bigint,
  'adminId' : Principal,
}
export interface AgentChain {
  'id' : bigint,
  'status' : AgentStatus,
  'tasks' : Array<AgentTask>,
  'goal' : string,
  'currentStep' : bigint,
}
export interface AgentMetrics {
  'totalTasks' : bigint,
  'completedTasks' : bigint,
  'avgDuration' : bigint,
  'failedTasks' : bigint,
}
export type AgentStatus = { 'idle' : null } |
  { 'complete' : null } |
  { 'failed' : null } |
  { 'running' : null };
export interface AgentStreamStep {
  'status' : string,
  'completedAt' : bigint,
  'output' : string,
  'startedAt' : bigint,
  'agentType' : string,
}
export interface AgentTask {
  'id' : bigint,
  'status' : AgentStatus,
  'output' : [] | [string],
  'agentType' : AgentType,
  'timestamp' : bigint,
  'input' : string,
}
export type AgentType = { 'memory' : null } |
  { 'research' : null } |
  { 'critic' : null } |
  { 'planner' : null } |
  { 'executor' : null };
export interface BoundingBox {
  'x' : number,
  'y' : number,
  'height' : number,
  'width' : number,
}
export interface CallInitRequest { 'toPhone' : string, 'message' : string }
export interface CallRecord {
  'id' : bigint,
  'status' : string,
  'duration' : bigint,
  'callerPhone' : string,
  'callSid' : string,
  'timestamp' : bigint,
  'transcript' : string,
}
export interface CameraFeed {
  'id' : bigint,
  'name' : string,
  'isActive' : boolean,
  'streamUrl' : string,
}
export interface ChatMessage { 'content' : string, 'role' : string }
export interface DetectionHistoryRecord {
  'id' : bigint,
  'objects' : Array<DetectionObject>,
  'timestamp' : bigint,
  'cameraId' : string,
}
export interface DetectionObject {
  'highAlert' : boolean,
  'bbox' : BoundingBox,
  'name' : string,
  'confidence' : number,
}
export type DocumentType = { 'pdf' : null } |
  { 'txt' : null } |
  { 'url' : null } |
  { 'docx' : null };
export interface DroneAlert {
  'id' : bigint,
  'droneId' : bigint,
  'alertType' : string,
  'description' : string,
  'timestamp' : bigint,
}
export interface DroneState {
  'id' : bigint,
  'lat' : number,
  'lng' : number,
  'status' : DroneStatus,
  'altitude' : number,
  'speed' : number,
  'timestamp' : bigint,
  'battery' : bigint,
}
export type DroneStatus = { 'emergency' : null } |
  { 'idle' : null } |
  { 'flying' : null } |
  { 'landing' : null };
export interface GeneticProfile {
  'technicalDepth' : number,
  'userId' : string,
  'preferences' : Array<UserPreference>,
  'dominantDomain' : string,
  'formalityLevel' : number,
  'dominantLanguage' : string,
  'lastAdapted' : bigint,
}
export interface GeofenceAlert {
  'id' : bigint,
  'alertType' : string,
  'assetId' : bigint,
  'timestamp' : bigint,
  'zoneId' : bigint,
}
export interface GeofenceZone {
  'id' : bigint,
  'name' : string,
  'isActive' : boolean,
  'radius' : number,
  'centerLat' : number,
  'centerLng' : number,
}
export interface Holding {
  'avgCost' : number,
  'quantity' : bigint,
  'symbol' : string,
}
export type IndexStatus = { 'pending' : null } |
  { 'indexed' : null } |
  { 'failed' : null };
export interface IoTDevice {
  'id' : bigint,
  'name' : string,
  'isOnline' : boolean,
  'state' : string,
  'deviceType' : string,
  'lastSeen' : bigint,
}
export interface KnowledgeChunk {
  'id' : bigint,
  'chunkIndex' : bigint,
  'text' : string,
  'embeddingVector' : Array<number>,
  'similarity' : number,
  'docId' : bigint,
}
export interface KnowledgeDocument {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'indexStatus' : IndexStatus,
  'userId' : Principal,
  'chunks' : Array<KnowledgeChunk>,
  'docType' : DocumentType,
  'uploadedAt' : bigint,
}
export interface KnowledgeResult { 'chunk' : KnowledgeChunk, 'score' : number }
export interface KnowledgeStats {
  'indexedDocs' : bigint,
  'totalChunks' : bigint,
  'totalDocuments' : bigint,
}
export type Language = { 'hindi' : null } |
  { 'nagpuri' : null } |
  { 'english' : null };
export interface LegalClause {
  'id' : bigint,
  'startPos' : bigint,
  'text' : string,
  'clauseType' : string,
  'docId' : bigint,
  'endPos' : bigint,
}
export interface LegalDocument {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'userId' : Principal,
  'clauses' : Array<LegalClause>,
  'summary' : [] | [string],
  'uploadedAt' : bigint,
}
export interface LegalExport {
  'content' : string,
  'docId' : bigint,
  'format' : string,
}
export type LoginResult = { 'ok' : UserProfile } |
  { 'err' : string };
export interface Message {
  'id' : bigint,
  'content' : string,
  'role' : string,
  'timestamp' : bigint,
}
export interface MqttCommand {
  'topic' : string,
  'action' : string,
  'payload' : string,
}
export interface MqttCommandResult {
  'deviceId' : bigint,
  'timestamp' : bigint,
  'newState' : string,
  'success' : boolean,
}
export interface MqttDevice {
  'id' : bigint,
  'topic' : string,
  'value' : number,
  'lastUpdate' : bigint,
  'isOnline' : boolean,
  'state' : string,
  'deviceType' : string,
}
export interface MqttDeviceHistory {
  'value' : number,
  'state' : string,
  'deviceId' : bigint,
  'timestamp' : bigint,
}
export interface Portfolio {
  'totalValue' : number,
  'userId' : string,
  'holdings' : Array<Holding>,
  'lastUpdated' : bigint,
}
export type RegisterResult = { 'ok' : UserProfile } |
  { 'err' : string };
export interface RevenueMetrics {
  'mrr' : number,
  'month' : string,
  'arpu' : number,
  'churnRate' : number,
  'tierBreakdown' : TierBreakdown,
}
export interface Settings {
  'personality' : string,
  'glowColor' : string,
  'apiKey' : string,
}
export interface StockPrice {
  'low' : number,
  'date' : bigint,
  'high' : number,
  'close' : number,
  'open' : number,
  'volume' : bigint,
  'symbol' : string,
}
export interface StockSymbol {
  'name' : string,
  'sector' : string,
  'symbol' : string,
}
export interface StreamChunk {
  'id' : bigint,
  'content' : string,
  'chunkIndex' : bigint,
  'isFinal' : boolean,
  'timestamp' : bigint,
}
export interface StreamSession {
  'id' : bigint,
  'status' : string,
  'userId' : Principal,
  'createdAt' : bigint,
  'agentSteps' : Array<AgentStreamStep>,
  'chunks' : Array<StreamChunk>,
}
export interface SubscriptionStatus {
  'active' : boolean,
  'tier' : SubscriptionTier,
  'startDate' : bigint,
}
export type SubscriptionTier = { 'pro' : null } |
  { 'enterprise' : null } |
  { 'free' : null };
export interface SystemMetrics {
  'mrr' : number,
  'activeUsers' : bigint,
  'totalMessages' : bigint,
  'totalVoiceCalls' : bigint,
  'totalUsers' : bigint,
  'totalAgentTasks' : bigint,
}
export interface TierBreakdown {
  'pro' : bigint,
  'enterprise' : bigint,
  'free' : bigint,
}
export interface TrackingAsset {
  'id' : bigint,
  'lat' : number,
  'lng' : number,
  'status' : string,
  'name' : string,
  'heading' : number,
  'speed' : number,
  'timestamp' : bigint,
  'battery' : [] | [bigint],
}
export interface Transaction {
  'id' : string,
  'action' : TransactionAction,
  'userId' : string,
  'note' : string,
  'timestamp' : bigint,
  'quantity' : bigint,
  'price' : number,
  'symbol' : string,
}
export type TransactionAction = { 'buy' : null } |
  { 'sell' : null };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UserId = Principal;
export interface UserMetrics {
  'userId' : Principal,
  'agentTaskCount' : bigint,
  'messageCount' : bigint,
  'lastActive' : bigint,
  'voiceCount' : bigint,
}
export interface UserPreference {
  'key' : string,
  'weight' : number,
  'value' : string,
  'userId' : string,
  'updatedAt' : bigint,
}
export interface UserProfile {
  'id' : UserId,
  'name' : string,
  'createdAt' : bigint,
  'role' : UserRole,
  'tier' : SubscriptionTier,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null };
export interface VoiceMatch {
  'name' : string,
  'profileId' : string,
  'confidence' : number,
}
export interface VoiceProfile {
  'id' : string,
  'relationship' : string,
  'mfccFeatures' : Array<number>,
  'userId' : string,
  'name' : string,
  'enrolledPhrases' : bigint,
  'enrolledAt' : bigint,
}
export interface VoiceSession {
  'id' : bigint,
  'synthesis' : string,
  'userId' : Principal,
  'language' : Language,
  'transcription' : string,
  'timestamp' : bigint,
}
export interface VoiceSettings {
  'continuousMode' : boolean,
  'autoPlay' : boolean,
  'language' : Language,
  'speed' : number,
  'pitch' : number,
}
export interface YoloDetectionRequest {
  'imageData' : string,
  'cameraId' : string,
}
export interface YoloDetectionResult {
  'objects' : Array<DetectionObject>,
  'timestamp' : bigint,
  'confidence' : number,
  'cameraId' : string,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  'addGeofenceZone' : ActorMethod<[string, number, number, number], bigint>,
  'addMessage' : ActorMethod<[string, string], Message>,
  'adminLogin' : ActorMethod<[string, string], LoginResult>,
  'askDocumentQuestion' : ActorMethod<[bigint, string], string>,
  'banUser' : ActorMethod<[Principal], boolean>,
  'callLLM' : ActorMethod<[Array<ChatMessage>, string, string], string>,
  'cancelSubscription' : ActorMethod<[], undefined>,
  'clearHistory' : ActorMethod<[], undefined>,
  'clearMyFaceData' : ActorMethod<[], boolean>,
  'createChain' : ActorMethod<[string], bigint>,
  'createStreamSession' : ActorMethod<[], StreamSession>,
  'deleteDocument' : ActorMethod<[bigint], boolean>,
  'deleteLegalDocument' : ActorMethod<[bigint], boolean>,
  'deleteVoiceProfile' : ActorMethod<[string, string], boolean>,
  'demoLogin' : ActorMethod<[], LoginResult>,
  'enrollFace' : ActorMethod<[string], boolean>,
  'enrollVoiceProfile' : ActorMethod<
    [string, string, string, Array<number>],
    VoiceProfile
  >,
  'executeSimulatedTrade' : ActorMethod<
    [string, string, TransactionAction, bigint],
    Transaction
  >,
  'exportAnalytics' : ActorMethod<[], string>,
  'exportDocumentSummary' : ActorMethod<[bigint, string], LegalExport>,
  'extractDocumentClauses' : ActorMethod<[bigint], Array<LegalClause>>,
  'getActiveStream' : ActorMethod<[], [] | [StreamSession]>,
  'getAdminLogs' : ActorMethod<[], Array<AdminLog>>,
  'getAgentMetrics' : ActorMethod<[], AgentMetrics>,
  'getCallLogs' : ActorMethod<[], Array<CallRecord>>,
  'getCallRecord' : ActorMethod<[bigint], [] | [CallRecord]>,
  'getCameraFeeds' : ActorMethod<[], Array<CameraFeed>>,
  'getChain' : ActorMethod<[bigint], [] | [AgentChain]>,
  'getDetectionAlerts' : ActorMethod<[], Array<DroneAlert>>,
  'getDetectionHistory' : ActorMethod<[], Array<DetectionHistoryRecord>>,
  'getDrone' : ActorMethod<[bigint], [] | [DroneState]>,
  'getGeneticProfile' : ActorMethod<[string], GeneticProfile>,
  'getGeofenceAlerts' : ActorMethod<[], Array<GeofenceAlert>>,
  'getHistory' : ActorMethod<[], Array<Message>>,
  'getKnowledgeStats' : ActorMethod<[], KnowledgeStats>,
  'getLegalDocument' : ActorMethod<[bigint], [] | [LegalDocument]>,
  'getMRRTrend' : ActorMethod<[bigint], Array<RevenueMetrics>>,
  'getMqttDeviceHistory' : ActorMethod<[bigint], Array<MqttDeviceHistory>>,
  'getMqttDevices' : ActorMethod<[], Array<MqttDevice>>,
  'getMyMetrics' : ActorMethod<[], UserMetrics>,
  'getPortfolio' : ActorMethod<[string], Portfolio>,
  'getRevenueMetrics' : ActorMethod<[string], RevenueMetrics>,
  'getSettings' : ActorMethod<[], Settings>,
  'getStockHistory' : ActorMethod<[string, bigint], Array<StockPrice>>,
  'getStockPrice' : ActorMethod<[string], StockPrice>,
  'getStockSymbols' : ActorMethod<[], Array<StockSymbol>>,
  'getStreamSession' : ActorMethod<[bigint], [] | [StreamSession]>,
  'getSubscriptionStatus' : ActorMethod<[], SubscriptionStatus>,
  'getSystemHealth' : ActorMethod<
    [],
    {
      'messagesCount' : bigint,
      'uptime' : bigint,
      'usersCount' : bigint,
      'agentTasksCount' : bigint,
    }
  >,
  'getSystemMetrics' : ActorMethod<[], SystemMetrics>,
  'getTrackingAsset' : ActorMethod<[bigint], [] | [TrackingAsset]>,
  'getTransactionHistory' : ActorMethod<[string], Array<Transaction>>,
  'getUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getUserRole' : ActorMethod<[], [] | [UserRole]>,
  'getUserSubscription' : ActorMethod<[], [] | [SubscriptionTier]>,
  'getVoiceSessions' : ActorMethod<[], Array<VoiceSession>>,
  'getVoiceSettings' : ActorMethod<[], VoiceSettings>,
  'hasFaceEnrolled' : ActorMethod<[], boolean>,
  'initCallModule' : ActorMethod<[], boolean>,
  'initDetectionModule' : ActorMethod<[], boolean>,
  'initMqttModule' : ActorMethod<[], boolean>,
  'listAllUsers' : ActorMethod<[], Array<UserProfile>>,
  'listChains' : ActorMethod<[], Array<AgentChain>>,
  'listDocuments' : ActorMethod<[], Array<KnowledgeDocument>>,
  'listDrones' : ActorMethod<[], Array<DroneState>>,
  'listEnrolledFaces' : ActorMethod<[], Array<Principal>>,
  'listGeofences' : ActorMethod<[], Array<GeofenceZone>>,
  'listIoTDevices' : ActorMethod<[], Array<IoTDevice>>,
  'listLegalDocuments' : ActorMethod<[], Array<LegalDocument>>,
  'listTrackingAssets' : ActorMethod<[], Array<TrackingAsset>>,
  'listVoiceProfiles' : ActorMethod<[string], Array<VoiceProfile>>,
  'logVoiceSession' : ActorMethod<[string, string, string], bigint>,
  'logout' : ActorMethod<[], undefined>,
  'makeCall' : ActorMethod<[CallInitRequest], CallRecord>,
  'matchVoiceProfile' : ActorMethod<[string, Array<number>], [] | [VoiceMatch]>,
  'recordInteraction' : ActorMethod<[string, Array<string>], undefined>,
  'register' : ActorMethod<[string, string], RegisterResult>,
  'runChain' : ActorMethod<[bigint], string>,
  'runYoloDetection' : ActorMethod<[YoloDetectionRequest], YoloDetectionResult>,
  'saveSettings' : ActorMethod<[string, string, string], undefined>,
  'saveVoiceSettings' : ActorMethod<[VoiceSettings], boolean>,
  'searchKnowledge' : ActorMethod<[string, bigint], Array<KnowledgeResult>>,
  'sendIoTCommand' : ActorMethod<[bigint, string, string], boolean>,
  'sendMqttCommand' : ActorMethod<[MqttCommand], MqttCommandResult>,
  'setDroneCommand' : ActorMethod<[bigint, string], boolean>,
  'simulateMovement' : ActorMethod<[], boolean>,
  'summarizeLegalDocument' : ActorMethod<[bigint], string>,
  'trackEvent' : ActorMethod<[string, string], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'translateForLanguage' : ActorMethod<[string, string], string>,
  'triggerReindex' : ActorMethod<[], boolean>,
  'triggerSimulation' : ActorMethod<[], boolean>,
  'twilioTransform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateAgentStep' : ActorMethod<[bigint, AgentStreamStep], boolean>,
  'updateGeneticPreference' : ActorMethod<
    [string, string, string, number],
    undefined
  >,
  'updateStreamChunk' : ActorMethod<[bigint, StreamChunk], boolean>,
  'updateSubscription' : ActorMethod<[SubscriptionTier], undefined>,
  'updateUserTier' : ActorMethod<[Principal, string], boolean>,
  'upgradeSubscription' : ActorMethod<[SubscriptionTier], boolean>,
  'uploadDocument' : ActorMethod<[string, string, string], bigint>,
  'uploadLegalDocument' : ActorMethod<[string, string], bigint>,
  'verifyFaceLogin' : ActorMethod<[string], [boolean, [] | [Principal]]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];