/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Message = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'role' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const UserId = IDL.Principal;
export const UserRole = IDL.Variant({ 'admin' : IDL.Null, 'user' : IDL.Null });
export const SubscriptionTier = IDL.Variant({
  'pro' : IDL.Null,
  'enterprise' : IDL.Null,
  'free' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'id' : UserId,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'role' : UserRole,
  'tier' : SubscriptionTier,
  'email' : IDL.Text,
});
export const LoginResult = IDL.Variant({
  'ok' : UserProfile,
  'err' : IDL.Text,
});
export const ChatMessage = IDL.Record({
  'content' : IDL.Text,
  'role' : IDL.Text,
});
export const AgentStreamStep = IDL.Record({
  'status' : IDL.Text,
  'completedAt' : IDL.Int,
  'output' : IDL.Text,
  'startedAt' : IDL.Int,
  'agentType' : IDL.Text,
});
export const StreamChunk = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'chunkIndex' : IDL.Nat,
  'isFinal' : IDL.Bool,
  'timestamp' : IDL.Int,
});
export const StreamSession = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'userId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'agentSteps' : IDL.Vec(AgentStreamStep),
  'chunks' : IDL.Vec(StreamChunk),
});
export const VoiceProfile = IDL.Record({
  'id' : IDL.Text,
  'relationship' : IDL.Text,
  'mfccFeatures' : IDL.Vec(IDL.Float64),
  'userId' : IDL.Text,
  'name' : IDL.Text,
  'enrolledPhrases' : IDL.Nat,
  'enrolledAt' : IDL.Int,
});
export const TransactionAction = IDL.Variant({
  'buy' : IDL.Null,
  'sell' : IDL.Null,
});
export const Transaction = IDL.Record({
  'id' : IDL.Text,
  'action' : TransactionAction,
  'userId' : IDL.Text,
  'note' : IDL.Text,
  'timestamp' : IDL.Int,
  'quantity' : IDL.Nat,
  'price' : IDL.Float64,
  'symbol' : IDL.Text,
});
export const LegalExport = IDL.Record({
  'content' : IDL.Text,
  'docId' : IDL.Nat,
  'format' : IDL.Text,
});
export const LegalClause = IDL.Record({
  'id' : IDL.Nat,
  'startPos' : IDL.Int,
  'text' : IDL.Text,
  'clauseType' : IDL.Text,
  'docId' : IDL.Nat,
  'endPos' : IDL.Int,
});
export const AdminAction = IDL.Variant({
  'updateTier' : IDL.Null,
  'banUser' : IDL.Null,
  'uploadDoc' : IDL.Null,
  'reindex' : IDL.Null,
  'deleteDoc' : IDL.Null,
});
export const AdminLog = IDL.Record({
  'id' : IDL.Nat,
  'action' : AdminAction,
  'target' : IDL.Text,
  'timestamp' : IDL.Int,
  'adminId' : IDL.Principal,
});
export const AgentMetrics = IDL.Record({
  'totalTasks' : IDL.Nat,
  'completedTasks' : IDL.Nat,
  'avgDuration' : IDL.Int,
  'failedTasks' : IDL.Nat,
});
export const CallRecord = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'duration' : IDL.Nat,
  'callerPhone' : IDL.Text,
  'callSid' : IDL.Text,
  'timestamp' : IDL.Int,
  'transcript' : IDL.Text,
});
export const CameraFeed = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'isActive' : IDL.Bool,
  'streamUrl' : IDL.Text,
});
export const AgentStatus = IDL.Variant({
  'idle' : IDL.Null,
  'complete' : IDL.Null,
  'failed' : IDL.Null,
  'running' : IDL.Null,
});
export const AgentType = IDL.Variant({
  'memory' : IDL.Null,
  'research' : IDL.Null,
  'critic' : IDL.Null,
  'planner' : IDL.Null,
  'executor' : IDL.Null,
});
export const AgentTask = IDL.Record({
  'id' : IDL.Nat,
  'status' : AgentStatus,
  'output' : IDL.Opt(IDL.Text),
  'agentType' : AgentType,
  'timestamp' : IDL.Int,
  'input' : IDL.Text,
});
export const AgentChain = IDL.Record({
  'id' : IDL.Nat,
  'status' : AgentStatus,
  'tasks' : IDL.Vec(AgentTask),
  'goal' : IDL.Text,
  'currentStep' : IDL.Nat,
});
export const DroneAlert = IDL.Record({
  'id' : IDL.Nat,
  'droneId' : IDL.Nat,
  'alertType' : IDL.Text,
  'description' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const BoundingBox = IDL.Record({
  'x' : IDL.Float64,
  'y' : IDL.Float64,
  'height' : IDL.Float64,
  'width' : IDL.Float64,
});
export const DetectionObject = IDL.Record({
  'highAlert' : IDL.Bool,
  'bbox' : BoundingBox,
  'name' : IDL.Text,
  'confidence' : IDL.Float64,
});
export const DetectionHistoryRecord = IDL.Record({
  'id' : IDL.Nat,
  'objects' : IDL.Vec(DetectionObject),
  'timestamp' : IDL.Int,
  'cameraId' : IDL.Text,
});
export const DroneStatus = IDL.Variant({
  'emergency' : IDL.Null,
  'idle' : IDL.Null,
  'flying' : IDL.Null,
  'landing' : IDL.Null,
});
export const DroneState = IDL.Record({
  'id' : IDL.Nat,
  'lat' : IDL.Float64,
  'lng' : IDL.Float64,
  'status' : DroneStatus,
  'altitude' : IDL.Float64,
  'speed' : IDL.Float64,
  'timestamp' : IDL.Int,
  'battery' : IDL.Int,
});
export const UserPreference = IDL.Record({
  'key' : IDL.Text,
  'weight' : IDL.Float64,
  'value' : IDL.Text,
  'userId' : IDL.Text,
  'updatedAt' : IDL.Int,
});
export const GeneticProfile = IDL.Record({
  'technicalDepth' : IDL.Float64,
  'userId' : IDL.Text,
  'preferences' : IDL.Vec(UserPreference),
  'dominantDomain' : IDL.Text,
  'formalityLevel' : IDL.Float64,
  'dominantLanguage' : IDL.Text,
  'lastAdapted' : IDL.Int,
});
export const GeofenceAlert = IDL.Record({
  'id' : IDL.Nat,
  'alertType' : IDL.Text,
  'assetId' : IDL.Nat,
  'timestamp' : IDL.Int,
  'zoneId' : IDL.Nat,
});
export const KnowledgeStats = IDL.Record({
  'indexedDocs' : IDL.Nat,
  'totalChunks' : IDL.Nat,
  'totalDocuments' : IDL.Nat,
});
export const LegalDocument = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'userId' : IDL.Principal,
  'clauses' : IDL.Vec(LegalClause),
  'summary' : IDL.Opt(IDL.Text),
  'uploadedAt' : IDL.Int,
});
export const TierBreakdown = IDL.Record({
  'pro' : IDL.Nat,
  'enterprise' : IDL.Nat,
  'free' : IDL.Nat,
});
export const RevenueMetrics = IDL.Record({
  'mrr' : IDL.Float64,
  'month' : IDL.Text,
  'arpu' : IDL.Float64,
  'churnRate' : IDL.Float64,
  'tierBreakdown' : TierBreakdown,
});
export const MqttDeviceHistory = IDL.Record({
  'value' : IDL.Float64,
  'state' : IDL.Text,
  'deviceId' : IDL.Nat,
  'timestamp' : IDL.Int,
});
export const MqttDevice = IDL.Record({
  'id' : IDL.Nat,
  'topic' : IDL.Text,
  'value' : IDL.Float64,
  'lastUpdate' : IDL.Int,
  'isOnline' : IDL.Bool,
  'state' : IDL.Text,
  'deviceType' : IDL.Text,
});
export const UserMetrics = IDL.Record({
  'userId' : IDL.Principal,
  'agentTaskCount' : IDL.Nat,
  'messageCount' : IDL.Nat,
  'lastActive' : IDL.Int,
  'voiceCount' : IDL.Nat,
});
export const Holding = IDL.Record({
  'avgCost' : IDL.Float64,
  'quantity' : IDL.Nat,
  'symbol' : IDL.Text,
});
export const Portfolio = IDL.Record({
  'totalValue' : IDL.Float64,
  'userId' : IDL.Text,
  'holdings' : IDL.Vec(Holding),
  'lastUpdated' : IDL.Int,
});
export const Settings = IDL.Record({
  'personality' : IDL.Text,
  'glowColor' : IDL.Text,
  'apiKey' : IDL.Text,
});
export const StockPrice = IDL.Record({
  'low' : IDL.Float64,
  'date' : IDL.Int,
  'high' : IDL.Float64,
  'close' : IDL.Float64,
  'open' : IDL.Float64,
  'volume' : IDL.Nat,
  'symbol' : IDL.Text,
});
export const StockSymbol = IDL.Record({
  'name' : IDL.Text,
  'sector' : IDL.Text,
  'symbol' : IDL.Text,
});
export const SubscriptionStatus = IDL.Record({
  'active' : IDL.Bool,
  'tier' : SubscriptionTier,
  'startDate' : IDL.Int,
});
export const SystemMetrics = IDL.Record({
  'mrr' : IDL.Float64,
  'activeUsers' : IDL.Nat,
  'totalMessages' : IDL.Nat,
  'totalVoiceCalls' : IDL.Nat,
  'totalUsers' : IDL.Nat,
  'totalAgentTasks' : IDL.Nat,
});
export const TrackingAsset = IDL.Record({
  'id' : IDL.Nat,
  'lat' : IDL.Float64,
  'lng' : IDL.Float64,
  'status' : IDL.Text,
  'name' : IDL.Text,
  'heading' : IDL.Float64,
  'speed' : IDL.Float64,
  'timestamp' : IDL.Int,
  'battery' : IDL.Opt(IDL.Int),
});
export const Language = IDL.Variant({
  'hindi' : IDL.Null,
  'nagpuri' : IDL.Null,
  'english' : IDL.Null,
});
export const VoiceSession = IDL.Record({
  'id' : IDL.Nat,
  'synthesis' : IDL.Text,
  'userId' : IDL.Principal,
  'language' : Language,
  'transcription' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const VoiceSettings = IDL.Record({
  'continuousMode' : IDL.Bool,
  'autoPlay' : IDL.Bool,
  'language' : Language,
  'speed' : IDL.Float64,
  'pitch' : IDL.Float64,
});
export const IndexStatus = IDL.Variant({
  'pending' : IDL.Null,
  'indexed' : IDL.Null,
  'failed' : IDL.Null,
});
export const KnowledgeChunk = IDL.Record({
  'id' : IDL.Nat,
  'chunkIndex' : IDL.Nat,
  'text' : IDL.Text,
  'embeddingVector' : IDL.Vec(IDL.Float64),
  'similarity' : IDL.Float64,
  'docId' : IDL.Nat,
});
export const DocumentType = IDL.Variant({
  'pdf' : IDL.Null,
  'txt' : IDL.Null,
  'url' : IDL.Null,
  'docx' : IDL.Null,
});
export const KnowledgeDocument = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'indexStatus' : IndexStatus,
  'userId' : IDL.Principal,
  'chunks' : IDL.Vec(KnowledgeChunk),
  'docType' : DocumentType,
  'uploadedAt' : IDL.Int,
});
export const GeofenceZone = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'isActive' : IDL.Bool,
  'radius' : IDL.Float64,
  'centerLat' : IDL.Float64,
  'centerLng' : IDL.Float64,
});
export const IoTDevice = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'isOnline' : IDL.Bool,
  'state' : IDL.Text,
  'deviceType' : IDL.Text,
  'lastSeen' : IDL.Int,
});
export const CallInitRequest = IDL.Record({
  'toPhone' : IDL.Text,
  'message' : IDL.Text,
});
export const VoiceMatch = IDL.Record({
  'name' : IDL.Text,
  'profileId' : IDL.Text,
  'confidence' : IDL.Float64,
});
export const RegisterResult = IDL.Variant({
  'ok' : UserProfile,
  'err' : IDL.Text,
});
export const YoloDetectionRequest = IDL.Record({
  'imageData' : IDL.Text,
  'cameraId' : IDL.Text,
});
export const YoloDetectionResult = IDL.Record({
  'objects' : IDL.Vec(DetectionObject),
  'timestamp' : IDL.Int,
  'confidence' : IDL.Float64,
  'cameraId' : IDL.Text,
});
export const KnowledgeResult = IDL.Record({
  'chunk' : KnowledgeChunk,
  'score' : IDL.Float64,
});
export const MqttCommand = IDL.Record({
  'topic' : IDL.Text,
  'action' : IDL.Text,
  'payload' : IDL.Text,
});
export const MqttCommandResult = IDL.Record({
  'deviceId' : IDL.Nat,
  'timestamp' : IDL.Int,
  'newState' : IDL.Text,
  'success' : IDL.Bool,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  'addGeofenceZone' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Float64, IDL.Float64],
      [IDL.Nat],
      [],
    ),
  'addMessage' : IDL.Func([IDL.Text, IDL.Text], [Message], []),
  'adminLogin' : IDL.Func([IDL.Text, IDL.Text], [LoginResult], []),
  'askDocumentQuestion' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Text], []),
  'banUser' : IDL.Func([IDL.Principal], [IDL.Bool], []),
  'callLLM' : IDL.Func(
      [IDL.Vec(ChatMessage), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'cancelSubscription' : IDL.Func([], [], []),
  'clearHistory' : IDL.Func([], [], []),
  'clearMyFaceData' : IDL.Func([], [IDL.Bool], []),
  'createChain' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'createStreamSession' : IDL.Func([], [StreamSession], []),
  'deleteDocument' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteLegalDocument' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteVoiceProfile' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'demoLogin' : IDL.Func([], [LoginResult], []),
  'enrollFace' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'enrollVoiceProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Float64)],
      [VoiceProfile],
      [],
    ),
  'executeSimulatedTrade' : IDL.Func(
      [IDL.Text, IDL.Text, TransactionAction, IDL.Nat],
      [Transaction],
      [],
    ),
  'exportAnalytics' : IDL.Func([], [IDL.Text], ['query']),
  'exportDocumentSummary' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [LegalExport],
      ['query'],
    ),
  'extractDocumentClauses' : IDL.Func([IDL.Nat], [IDL.Vec(LegalClause)], []),
  'getActiveStream' : IDL.Func([], [IDL.Opt(StreamSession)], ['query']),
  'getAdminLogs' : IDL.Func([], [IDL.Vec(AdminLog)], ['query']),
  'getAgentMetrics' : IDL.Func([], [AgentMetrics], ['query']),
  'getCallLogs' : IDL.Func([], [IDL.Vec(CallRecord)], ['query']),
  'getCallRecord' : IDL.Func([IDL.Nat], [IDL.Opt(CallRecord)], ['query']),
  'getCameraFeeds' : IDL.Func([], [IDL.Vec(CameraFeed)], ['query']),
  'getChain' : IDL.Func([IDL.Nat], [IDL.Opt(AgentChain)], ['query']),
  'getDetectionAlerts' : IDL.Func([], [IDL.Vec(DroneAlert)], ['query']),
  'getDetectionHistory' : IDL.Func(
      [],
      [IDL.Vec(DetectionHistoryRecord)],
      ['query'],
    ),
  'getDrone' : IDL.Func([IDL.Nat], [IDL.Opt(DroneState)], ['query']),
  'getGeneticProfile' : IDL.Func([IDL.Text], [GeneticProfile], ['query']),
  'getGeofenceAlerts' : IDL.Func([], [IDL.Vec(GeofenceAlert)], ['query']),
  'getHistory' : IDL.Func([], [IDL.Vec(Message)], ['query']),
  'getKnowledgeStats' : IDL.Func([], [KnowledgeStats], ['query']),
  'getLegalDocument' : IDL.Func([IDL.Nat], [IDL.Opt(LegalDocument)], ['query']),
  'getMRRTrend' : IDL.Func([IDL.Nat], [IDL.Vec(RevenueMetrics)], ['query']),
  'getMqttDeviceHistory' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(MqttDeviceHistory)],
      ['query'],
    ),
  'getMqttDevices' : IDL.Func([], [IDL.Vec(MqttDevice)], ['query']),
  'getMyMetrics' : IDL.Func([], [UserMetrics], ['query']),
  'getPortfolio' : IDL.Func([IDL.Text], [Portfolio], ['query']),
  'getRevenueMetrics' : IDL.Func([IDL.Text], [RevenueMetrics], ['query']),
  'getSettings' : IDL.Func([], [Settings], ['query']),
  'getStockHistory' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Vec(StockPrice)],
      ['query'],
    ),
  'getStockPrice' : IDL.Func([IDL.Text], [StockPrice], ['query']),
  'getStockSymbols' : IDL.Func([], [IDL.Vec(StockSymbol)], ['query']),
  'getStreamSession' : IDL.Func([IDL.Nat], [IDL.Opt(StreamSession)], ['query']),
  'getSubscriptionStatus' : IDL.Func([], [SubscriptionStatus], ['query']),
  'getSystemHealth' : IDL.Func(
      [],
      [
        IDL.Record({
          'messagesCount' : IDL.Nat,
          'uptime' : IDL.Int,
          'usersCount' : IDL.Nat,
          'agentTasksCount' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getSystemMetrics' : IDL.Func([], [SystemMetrics], ['query']),
  'getTrackingAsset' : IDL.Func([IDL.Nat], [IDL.Opt(TrackingAsset)], ['query']),
  'getTransactionHistory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Transaction)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getUserRole' : IDL.Func([], [IDL.Opt(UserRole)], ['query']),
  'getUserSubscription' : IDL.Func([], [IDL.Opt(SubscriptionTier)], ['query']),
  'getVoiceSessions' : IDL.Func([], [IDL.Vec(VoiceSession)], ['query']),
  'getVoiceSettings' : IDL.Func([], [VoiceSettings], ['query']),
  'hasFaceEnrolled' : IDL.Func([], [IDL.Bool], ['query']),
  'initCallModule' : IDL.Func([], [IDL.Bool], []),
  'initDetectionModule' : IDL.Func([], [IDL.Bool], []),
  'initMqttModule' : IDL.Func([], [IDL.Bool], []),
  'listAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'listChains' : IDL.Func([], [IDL.Vec(AgentChain)], ['query']),
  'listDocuments' : IDL.Func([], [IDL.Vec(KnowledgeDocument)], ['query']),
  'listDrones' : IDL.Func([], [IDL.Vec(DroneState)], ['query']),
  'listEnrolledFaces' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'listGeofences' : IDL.Func([], [IDL.Vec(GeofenceZone)], ['query']),
  'listIoTDevices' : IDL.Func([], [IDL.Vec(IoTDevice)], ['query']),
  'listLegalDocuments' : IDL.Func([], [IDL.Vec(LegalDocument)], ['query']),
  'listTrackingAssets' : IDL.Func([], [IDL.Vec(TrackingAsset)], ['query']),
  'listVoiceProfiles' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(VoiceProfile)],
      ['query'],
    ),
  'logVoiceSession' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'logout' : IDL.Func([], [], []),
  'makeCall' : IDL.Func([CallInitRequest], [CallRecord], []),
  'matchVoiceProfile' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Float64)],
      [IDL.Opt(VoiceMatch)],
      ['query'],
    ),
  'recordInteraction' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [], []),
  'register' : IDL.Func([IDL.Text, IDL.Text], [RegisterResult], []),
  'runChain' : IDL.Func([IDL.Nat], [IDL.Text], []),
  'runYoloDetection' : IDL.Func(
      [YoloDetectionRequest],
      [YoloDetectionResult],
      [],
    ),
  'saveSettings' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'saveVoiceSettings' : IDL.Func([VoiceSettings], [IDL.Bool], []),
  'searchKnowledge' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Vec(KnowledgeResult)],
      [],
    ),
  'sendIoTCommand' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [IDL.Bool], []),
  'sendMqttCommand' : IDL.Func([MqttCommand], [MqttCommandResult], []),
  'setDroneCommand' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
  'simulateMovement' : IDL.Func([], [IDL.Bool], []),
  'summarizeLegalDocument' : IDL.Func([IDL.Nat], [IDL.Text], []),
  'trackEvent' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'translateForLanguage' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'triggerReindex' : IDL.Func([], [IDL.Bool], []),
  'triggerSimulation' : IDL.Func([], [IDL.Bool], []),
  'twilioTransform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateAgentStep' : IDL.Func([IDL.Nat, AgentStreamStep], [IDL.Bool], []),
  'updateGeneticPreference' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Float64],
      [],
      [],
    ),
  'updateStreamChunk' : IDL.Func([IDL.Nat, StreamChunk], [IDL.Bool], []),
  'updateSubscription' : IDL.Func([SubscriptionTier], [], []),
  'updateUserTier' : IDL.Func([IDL.Principal, IDL.Text], [IDL.Bool], []),
  'upgradeSubscription' : IDL.Func([SubscriptionTier], [IDL.Bool], []),
  'uploadDocument' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'uploadLegalDocument' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'verifyFaceLogin' : IDL.Func(
      [IDL.Text],
      [IDL.Bool, IDL.Opt(IDL.Principal)],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Message = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'role' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const UserId = IDL.Principal;
  const UserRole = IDL.Variant({ 'admin' : IDL.Null, 'user' : IDL.Null });
  const SubscriptionTier = IDL.Variant({
    'pro' : IDL.Null,
    'enterprise' : IDL.Null,
    'free' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'id' : UserId,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'role' : UserRole,
    'tier' : SubscriptionTier,
    'email' : IDL.Text,
  });
  const LoginResult = IDL.Variant({ 'ok' : UserProfile, 'err' : IDL.Text });
  const ChatMessage = IDL.Record({ 'content' : IDL.Text, 'role' : IDL.Text });
  const AgentStreamStep = IDL.Record({
    'status' : IDL.Text,
    'completedAt' : IDL.Int,
    'output' : IDL.Text,
    'startedAt' : IDL.Int,
    'agentType' : IDL.Text,
  });
  const StreamChunk = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'chunkIndex' : IDL.Nat,
    'isFinal' : IDL.Bool,
    'timestamp' : IDL.Int,
  });
  const StreamSession = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'userId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'agentSteps' : IDL.Vec(AgentStreamStep),
    'chunks' : IDL.Vec(StreamChunk),
  });
  const VoiceProfile = IDL.Record({
    'id' : IDL.Text,
    'relationship' : IDL.Text,
    'mfccFeatures' : IDL.Vec(IDL.Float64),
    'userId' : IDL.Text,
    'name' : IDL.Text,
    'enrolledPhrases' : IDL.Nat,
    'enrolledAt' : IDL.Int,
  });
  const TransactionAction = IDL.Variant({
    'buy' : IDL.Null,
    'sell' : IDL.Null,
  });
  const Transaction = IDL.Record({
    'id' : IDL.Text,
    'action' : TransactionAction,
    'userId' : IDL.Text,
    'note' : IDL.Text,
    'timestamp' : IDL.Int,
    'quantity' : IDL.Nat,
    'price' : IDL.Float64,
    'symbol' : IDL.Text,
  });
  const LegalExport = IDL.Record({
    'content' : IDL.Text,
    'docId' : IDL.Nat,
    'format' : IDL.Text,
  });
  const LegalClause = IDL.Record({
    'id' : IDL.Nat,
    'startPos' : IDL.Int,
    'text' : IDL.Text,
    'clauseType' : IDL.Text,
    'docId' : IDL.Nat,
    'endPos' : IDL.Int,
  });
  const AdminAction = IDL.Variant({
    'updateTier' : IDL.Null,
    'banUser' : IDL.Null,
    'uploadDoc' : IDL.Null,
    'reindex' : IDL.Null,
    'deleteDoc' : IDL.Null,
  });
  const AdminLog = IDL.Record({
    'id' : IDL.Nat,
    'action' : AdminAction,
    'target' : IDL.Text,
    'timestamp' : IDL.Int,
    'adminId' : IDL.Principal,
  });
  const AgentMetrics = IDL.Record({
    'totalTasks' : IDL.Nat,
    'completedTasks' : IDL.Nat,
    'avgDuration' : IDL.Int,
    'failedTasks' : IDL.Nat,
  });
  const CallRecord = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'duration' : IDL.Nat,
    'callerPhone' : IDL.Text,
    'callSid' : IDL.Text,
    'timestamp' : IDL.Int,
    'transcript' : IDL.Text,
  });
  const CameraFeed = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'isActive' : IDL.Bool,
    'streamUrl' : IDL.Text,
  });
  const AgentStatus = IDL.Variant({
    'idle' : IDL.Null,
    'complete' : IDL.Null,
    'failed' : IDL.Null,
    'running' : IDL.Null,
  });
  const AgentType = IDL.Variant({
    'memory' : IDL.Null,
    'research' : IDL.Null,
    'critic' : IDL.Null,
    'planner' : IDL.Null,
    'executor' : IDL.Null,
  });
  const AgentTask = IDL.Record({
    'id' : IDL.Nat,
    'status' : AgentStatus,
    'output' : IDL.Opt(IDL.Text),
    'agentType' : AgentType,
    'timestamp' : IDL.Int,
    'input' : IDL.Text,
  });
  const AgentChain = IDL.Record({
    'id' : IDL.Nat,
    'status' : AgentStatus,
    'tasks' : IDL.Vec(AgentTask),
    'goal' : IDL.Text,
    'currentStep' : IDL.Nat,
  });
  const DroneAlert = IDL.Record({
    'id' : IDL.Nat,
    'droneId' : IDL.Nat,
    'alertType' : IDL.Text,
    'description' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const BoundingBox = IDL.Record({
    'x' : IDL.Float64,
    'y' : IDL.Float64,
    'height' : IDL.Float64,
    'width' : IDL.Float64,
  });
  const DetectionObject = IDL.Record({
    'highAlert' : IDL.Bool,
    'bbox' : BoundingBox,
    'name' : IDL.Text,
    'confidence' : IDL.Float64,
  });
  const DetectionHistoryRecord = IDL.Record({
    'id' : IDL.Nat,
    'objects' : IDL.Vec(DetectionObject),
    'timestamp' : IDL.Int,
    'cameraId' : IDL.Text,
  });
  const DroneStatus = IDL.Variant({
    'emergency' : IDL.Null,
    'idle' : IDL.Null,
    'flying' : IDL.Null,
    'landing' : IDL.Null,
  });
  const DroneState = IDL.Record({
    'id' : IDL.Nat,
    'lat' : IDL.Float64,
    'lng' : IDL.Float64,
    'status' : DroneStatus,
    'altitude' : IDL.Float64,
    'speed' : IDL.Float64,
    'timestamp' : IDL.Int,
    'battery' : IDL.Int,
  });
  const UserPreference = IDL.Record({
    'key' : IDL.Text,
    'weight' : IDL.Float64,
    'value' : IDL.Text,
    'userId' : IDL.Text,
    'updatedAt' : IDL.Int,
  });
  const GeneticProfile = IDL.Record({
    'technicalDepth' : IDL.Float64,
    'userId' : IDL.Text,
    'preferences' : IDL.Vec(UserPreference),
    'dominantDomain' : IDL.Text,
    'formalityLevel' : IDL.Float64,
    'dominantLanguage' : IDL.Text,
    'lastAdapted' : IDL.Int,
  });
  const GeofenceAlert = IDL.Record({
    'id' : IDL.Nat,
    'alertType' : IDL.Text,
    'assetId' : IDL.Nat,
    'timestamp' : IDL.Int,
    'zoneId' : IDL.Nat,
  });
  const KnowledgeStats = IDL.Record({
    'indexedDocs' : IDL.Nat,
    'totalChunks' : IDL.Nat,
    'totalDocuments' : IDL.Nat,
  });
  const LegalDocument = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'userId' : IDL.Principal,
    'clauses' : IDL.Vec(LegalClause),
    'summary' : IDL.Opt(IDL.Text),
    'uploadedAt' : IDL.Int,
  });
  const TierBreakdown = IDL.Record({
    'pro' : IDL.Nat,
    'enterprise' : IDL.Nat,
    'free' : IDL.Nat,
  });
  const RevenueMetrics = IDL.Record({
    'mrr' : IDL.Float64,
    'month' : IDL.Text,
    'arpu' : IDL.Float64,
    'churnRate' : IDL.Float64,
    'tierBreakdown' : TierBreakdown,
  });
  const MqttDeviceHistory = IDL.Record({
    'value' : IDL.Float64,
    'state' : IDL.Text,
    'deviceId' : IDL.Nat,
    'timestamp' : IDL.Int,
  });
  const MqttDevice = IDL.Record({
    'id' : IDL.Nat,
    'topic' : IDL.Text,
    'value' : IDL.Float64,
    'lastUpdate' : IDL.Int,
    'isOnline' : IDL.Bool,
    'state' : IDL.Text,
    'deviceType' : IDL.Text,
  });
  const UserMetrics = IDL.Record({
    'userId' : IDL.Principal,
    'agentTaskCount' : IDL.Nat,
    'messageCount' : IDL.Nat,
    'lastActive' : IDL.Int,
    'voiceCount' : IDL.Nat,
  });
  const Holding = IDL.Record({
    'avgCost' : IDL.Float64,
    'quantity' : IDL.Nat,
    'symbol' : IDL.Text,
  });
  const Portfolio = IDL.Record({
    'totalValue' : IDL.Float64,
    'userId' : IDL.Text,
    'holdings' : IDL.Vec(Holding),
    'lastUpdated' : IDL.Int,
  });
  const Settings = IDL.Record({
    'personality' : IDL.Text,
    'glowColor' : IDL.Text,
    'apiKey' : IDL.Text,
  });
  const StockPrice = IDL.Record({
    'low' : IDL.Float64,
    'date' : IDL.Int,
    'high' : IDL.Float64,
    'close' : IDL.Float64,
    'open' : IDL.Float64,
    'volume' : IDL.Nat,
    'symbol' : IDL.Text,
  });
  const StockSymbol = IDL.Record({
    'name' : IDL.Text,
    'sector' : IDL.Text,
    'symbol' : IDL.Text,
  });
  const SubscriptionStatus = IDL.Record({
    'active' : IDL.Bool,
    'tier' : SubscriptionTier,
    'startDate' : IDL.Int,
  });
  const SystemMetrics = IDL.Record({
    'mrr' : IDL.Float64,
    'activeUsers' : IDL.Nat,
    'totalMessages' : IDL.Nat,
    'totalVoiceCalls' : IDL.Nat,
    'totalUsers' : IDL.Nat,
    'totalAgentTasks' : IDL.Nat,
  });
  const TrackingAsset = IDL.Record({
    'id' : IDL.Nat,
    'lat' : IDL.Float64,
    'lng' : IDL.Float64,
    'status' : IDL.Text,
    'name' : IDL.Text,
    'heading' : IDL.Float64,
    'speed' : IDL.Float64,
    'timestamp' : IDL.Int,
    'battery' : IDL.Opt(IDL.Int),
  });
  const Language = IDL.Variant({
    'hindi' : IDL.Null,
    'nagpuri' : IDL.Null,
    'english' : IDL.Null,
  });
  const VoiceSession = IDL.Record({
    'id' : IDL.Nat,
    'synthesis' : IDL.Text,
    'userId' : IDL.Principal,
    'language' : Language,
    'transcription' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const VoiceSettings = IDL.Record({
    'continuousMode' : IDL.Bool,
    'autoPlay' : IDL.Bool,
    'language' : Language,
    'speed' : IDL.Float64,
    'pitch' : IDL.Float64,
  });
  const IndexStatus = IDL.Variant({
    'pending' : IDL.Null,
    'indexed' : IDL.Null,
    'failed' : IDL.Null,
  });
  const KnowledgeChunk = IDL.Record({
    'id' : IDL.Nat,
    'chunkIndex' : IDL.Nat,
    'text' : IDL.Text,
    'embeddingVector' : IDL.Vec(IDL.Float64),
    'similarity' : IDL.Float64,
    'docId' : IDL.Nat,
  });
  const DocumentType = IDL.Variant({
    'pdf' : IDL.Null,
    'txt' : IDL.Null,
    'url' : IDL.Null,
    'docx' : IDL.Null,
  });
  const KnowledgeDocument = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'indexStatus' : IndexStatus,
    'userId' : IDL.Principal,
    'chunks' : IDL.Vec(KnowledgeChunk),
    'docType' : DocumentType,
    'uploadedAt' : IDL.Int,
  });
  const GeofenceZone = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'isActive' : IDL.Bool,
    'radius' : IDL.Float64,
    'centerLat' : IDL.Float64,
    'centerLng' : IDL.Float64,
  });
  const IoTDevice = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'isOnline' : IDL.Bool,
    'state' : IDL.Text,
    'deviceType' : IDL.Text,
    'lastSeen' : IDL.Int,
  });
  const CallInitRequest = IDL.Record({
    'toPhone' : IDL.Text,
    'message' : IDL.Text,
  });
  const VoiceMatch = IDL.Record({
    'name' : IDL.Text,
    'profileId' : IDL.Text,
    'confidence' : IDL.Float64,
  });
  const RegisterResult = IDL.Variant({ 'ok' : UserProfile, 'err' : IDL.Text });
  const YoloDetectionRequest = IDL.Record({
    'imageData' : IDL.Text,
    'cameraId' : IDL.Text,
  });
  const YoloDetectionResult = IDL.Record({
    'objects' : IDL.Vec(DetectionObject),
    'timestamp' : IDL.Int,
    'confidence' : IDL.Float64,
    'cameraId' : IDL.Text,
  });
  const KnowledgeResult = IDL.Record({
    'chunk' : KnowledgeChunk,
    'score' : IDL.Float64,
  });
  const MqttCommand = IDL.Record({
    'topic' : IDL.Text,
    'action' : IDL.Text,
    'payload' : IDL.Text,
  });
  const MqttCommandResult = IDL.Record({
    'deviceId' : IDL.Nat,
    'timestamp' : IDL.Int,
    'newState' : IDL.Text,
    'success' : IDL.Bool,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    'addGeofenceZone' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Float64, IDL.Float64],
        [IDL.Nat],
        [],
      ),
    'addMessage' : IDL.Func([IDL.Text, IDL.Text], [Message], []),
    'adminLogin' : IDL.Func([IDL.Text, IDL.Text], [LoginResult], []),
    'askDocumentQuestion' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Text], []),
    'banUser' : IDL.Func([IDL.Principal], [IDL.Bool], []),
    'callLLM' : IDL.Func(
        [IDL.Vec(ChatMessage), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'cancelSubscription' : IDL.Func([], [], []),
    'clearHistory' : IDL.Func([], [], []),
    'clearMyFaceData' : IDL.Func([], [IDL.Bool], []),
    'createChain' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'createStreamSession' : IDL.Func([], [StreamSession], []),
    'deleteDocument' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteLegalDocument' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteVoiceProfile' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'demoLogin' : IDL.Func([], [LoginResult], []),
    'enrollFace' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'enrollVoiceProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Float64)],
        [VoiceProfile],
        [],
      ),
    'executeSimulatedTrade' : IDL.Func(
        [IDL.Text, IDL.Text, TransactionAction, IDL.Nat],
        [Transaction],
        [],
      ),
    'exportAnalytics' : IDL.Func([], [IDL.Text], ['query']),
    'exportDocumentSummary' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [LegalExport],
        ['query'],
      ),
    'extractDocumentClauses' : IDL.Func([IDL.Nat], [IDL.Vec(LegalClause)], []),
    'getActiveStream' : IDL.Func([], [IDL.Opt(StreamSession)], ['query']),
    'getAdminLogs' : IDL.Func([], [IDL.Vec(AdminLog)], ['query']),
    'getAgentMetrics' : IDL.Func([], [AgentMetrics], ['query']),
    'getCallLogs' : IDL.Func([], [IDL.Vec(CallRecord)], ['query']),
    'getCallRecord' : IDL.Func([IDL.Nat], [IDL.Opt(CallRecord)], ['query']),
    'getCameraFeeds' : IDL.Func([], [IDL.Vec(CameraFeed)], ['query']),
    'getChain' : IDL.Func([IDL.Nat], [IDL.Opt(AgentChain)], ['query']),
    'getDetectionAlerts' : IDL.Func([], [IDL.Vec(DroneAlert)], ['query']),
    'getDetectionHistory' : IDL.Func(
        [],
        [IDL.Vec(DetectionHistoryRecord)],
        ['query'],
      ),
    'getDrone' : IDL.Func([IDL.Nat], [IDL.Opt(DroneState)], ['query']),
    'getGeneticProfile' : IDL.Func([IDL.Text], [GeneticProfile], ['query']),
    'getGeofenceAlerts' : IDL.Func([], [IDL.Vec(GeofenceAlert)], ['query']),
    'getHistory' : IDL.Func([], [IDL.Vec(Message)], ['query']),
    'getKnowledgeStats' : IDL.Func([], [KnowledgeStats], ['query']),
    'getLegalDocument' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(LegalDocument)],
        ['query'],
      ),
    'getMRRTrend' : IDL.Func([IDL.Nat], [IDL.Vec(RevenueMetrics)], ['query']),
    'getMqttDeviceHistory' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(MqttDeviceHistory)],
        ['query'],
      ),
    'getMqttDevices' : IDL.Func([], [IDL.Vec(MqttDevice)], ['query']),
    'getMyMetrics' : IDL.Func([], [UserMetrics], ['query']),
    'getPortfolio' : IDL.Func([IDL.Text], [Portfolio], ['query']),
    'getRevenueMetrics' : IDL.Func([IDL.Text], [RevenueMetrics], ['query']),
    'getSettings' : IDL.Func([], [Settings], ['query']),
    'getStockHistory' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Vec(StockPrice)],
        ['query'],
      ),
    'getStockPrice' : IDL.Func([IDL.Text], [StockPrice], ['query']),
    'getStockSymbols' : IDL.Func([], [IDL.Vec(StockSymbol)], ['query']),
    'getStreamSession' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(StreamSession)],
        ['query'],
      ),
    'getSubscriptionStatus' : IDL.Func([], [SubscriptionStatus], ['query']),
    'getSystemHealth' : IDL.Func(
        [],
        [
          IDL.Record({
            'messagesCount' : IDL.Nat,
            'uptime' : IDL.Int,
            'usersCount' : IDL.Nat,
            'agentTasksCount' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getSystemMetrics' : IDL.Func([], [SystemMetrics], ['query']),
    'getTrackingAsset' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(TrackingAsset)],
        ['query'],
      ),
    'getTransactionHistory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getUserRole' : IDL.Func([], [IDL.Opt(UserRole)], ['query']),
    'getUserSubscription' : IDL.Func(
        [],
        [IDL.Opt(SubscriptionTier)],
        ['query'],
      ),
    'getVoiceSessions' : IDL.Func([], [IDL.Vec(VoiceSession)], ['query']),
    'getVoiceSettings' : IDL.Func([], [VoiceSettings], ['query']),
    'hasFaceEnrolled' : IDL.Func([], [IDL.Bool], ['query']),
    'initCallModule' : IDL.Func([], [IDL.Bool], []),
    'initDetectionModule' : IDL.Func([], [IDL.Bool], []),
    'initMqttModule' : IDL.Func([], [IDL.Bool], []),
    'listAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'listChains' : IDL.Func([], [IDL.Vec(AgentChain)], ['query']),
    'listDocuments' : IDL.Func([], [IDL.Vec(KnowledgeDocument)], ['query']),
    'listDrones' : IDL.Func([], [IDL.Vec(DroneState)], ['query']),
    'listEnrolledFaces' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'listGeofences' : IDL.Func([], [IDL.Vec(GeofenceZone)], ['query']),
    'listIoTDevices' : IDL.Func([], [IDL.Vec(IoTDevice)], ['query']),
    'listLegalDocuments' : IDL.Func([], [IDL.Vec(LegalDocument)], ['query']),
    'listTrackingAssets' : IDL.Func([], [IDL.Vec(TrackingAsset)], ['query']),
    'listVoiceProfiles' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(VoiceProfile)],
        ['query'],
      ),
    'logVoiceSession' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
    'logout' : IDL.Func([], [], []),
    'makeCall' : IDL.Func([CallInitRequest], [CallRecord], []),
    'matchVoiceProfile' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Float64)],
        [IDL.Opt(VoiceMatch)],
        ['query'],
      ),
    'recordInteraction' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [], []),
    'register' : IDL.Func([IDL.Text, IDL.Text], [RegisterResult], []),
    'runChain' : IDL.Func([IDL.Nat], [IDL.Text], []),
    'runYoloDetection' : IDL.Func(
        [YoloDetectionRequest],
        [YoloDetectionResult],
        [],
      ),
    'saveSettings' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'saveVoiceSettings' : IDL.Func([VoiceSettings], [IDL.Bool], []),
    'searchKnowledge' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Vec(KnowledgeResult)],
        [],
      ),
    'sendIoTCommand' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [IDL.Bool], []),
    'sendMqttCommand' : IDL.Func([MqttCommand], [MqttCommandResult], []),
    'setDroneCommand' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
    'simulateMovement' : IDL.Func([], [IDL.Bool], []),
    'summarizeLegalDocument' : IDL.Func([IDL.Nat], [IDL.Text], []),
    'trackEvent' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'translateForLanguage' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'triggerReindex' : IDL.Func([], [IDL.Bool], []),
    'triggerSimulation' : IDL.Func([], [IDL.Bool], []),
    'twilioTransform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateAgentStep' : IDL.Func([IDL.Nat, AgentStreamStep], [IDL.Bool], []),
    'updateGeneticPreference' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Float64],
        [],
        [],
      ),
    'updateStreamChunk' : IDL.Func([IDL.Nat, StreamChunk], [IDL.Bool], []),
    'updateSubscription' : IDL.Func([SubscriptionTier], [], []),
    'updateUserTier' : IDL.Func([IDL.Principal, IDL.Text], [IDL.Bool], []),
    'upgradeSubscription' : IDL.Func([SubscriptionTier], [IDL.Bool], []),
    'uploadDocument' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
    'uploadLegalDocument' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'verifyFaceLogin' : IDL.Func(
        [IDL.Text],
        [IDL.Bool, IDL.Opt(IDL.Principal)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };